# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'client-serverVK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for client-serverVK
pod 'Alamofire'
pod 'SwiftKeychainWrapper'
pod 'SDWebImage'
pod 'SwiftyJSON'
pod 'RealmSwift'

end
